### ISSUE TITLE
Not able to launch multiple instances.

### ISSUE THREAD

**Issue by himanshkumar** [zwindler/ansible-deploy-azure#1]
Using this script we cannot launch multiple instances. It gives error:
TASK [Create a test-nicX network interface for each VM] *********************************************************
changed: [localhost] => (item=1)
failed: [localhost] (item=2) => {"changed": false, "item": "2", "msg": "Error creating or updating network interface test-nic2 - Azure Error: PublicIPAddressInUse\nMessage: Resource /subscriptions/6b477b69-a65e-435c-8ca0-7010688a636e/resourceGroups/test-rg/providers/Microsoft.Network/networkInterfaces/test-nic2/ipConfigurations/ipconfig is referencing public IP address /subscriptions/6b477b69-a65e-435c-8cr0-70106d88636e/resourceGroups/test-rg/providers/Microsoft.Network/publicIPAddresses/test-ip that is already allocated to resource /subscriptions/6b477b69-a65e-435c-8ca0-70106d88636e/resourceGroups/test-rg/providers/Microsoft.Network/networkInterfaces/test-nic1/ipConfigurations/ipconfig."}

**Comment by zwindler** [comment]
From the error message, I found that I forgot to add a number to the IP address generated when we are creating nics

The nics were using the same IP over and over

Should be fixed in latest code (commit 99cba6765fe03310e45ac1921cc2183a8a704fa6)
